dryRun: false

extraArgs: {}

conditions: {}

replicaCount: 1

image:
  repository: hapu2000/draino
  tag: latetest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 16Mi

# Add these annotations to all pods
podAnnotations: {}
  # name: value
  # prometheus.io/scrape: 'true'
  # prometheus.io/port: '9102'

# Add these labels to all pods
podLabels: {}
  # name: value

rbac:
  create: true
  serviceAccountName:

nodeSelector: {}

tolerations: []

affinity: {}
  # nodeAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 100
  #       preference:
  #         matchExpressions:
  #           - key: "kubernetes.io/arch"
  #             operator: In
  #             values:
  #               - arm64

# Security Context policies for pods
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  fsGroup: 101
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 100

containerSecurityContext:
  privileged: false
  readOnlyRootFilesystem: true
